var Twit = require('twit')
// credentials
var T = new Twit({
    consumer_key:         'rlEx2UxPrhF3pJPAhWBbevO1f'
  , consumer_secret:      'Jo54Cc7Up2zTQ70dtXAkkiO4HfGVgYW09ZGVHzRsmRqtHfdNXP'
  , access_token:         '2609565380-n1dKL8vT8POWit8uhDmBPPYiJy3uzq34DszHHkF'
  , access_token_secret:  '0RgW9iBivnQa2lvgyZJ2zC6jlKVmxMxnaLlsl7cxfFzxv'
})


   
//   ----------------------------
   var Mingleinterval, j = 0;

function dostuff() {
    
if(rand <= 0.55) { //  make a friend
    bot.mingle(function(err, reply) {
      if(err) return handleError(err);

      var name = reply.screen_name;
      console.log('\nMingle: followed @' + name);
    });
  } else {                  //  prune a friend
    bot.prune(function(err, reply) {
      if(err) return handleError(err);

      var name = reply.screen_name
      console.log('\nPrune: unfollowed @'+ name);
    });
  }

    if(j < twitterArray.length) j++;
    else clearInterval(Mingleinterval);
}

interval = setInterval(dostuff, 300000 /*86400000*/);
   
   
   
   
   
   
   
   
   


var twitterArray =["Should creative talents be well paid? ",
"Should governments ‘nudge’ their citizens?",
"In Renaissance Venice, it was illegal for a merchant to dress as a peasant to fool buyers ",
"that the offered produce was home grown What kinds of regulation are needed to control modern retailers?",
"What is the Euro’s most fundamental problem?",
"How might we be changed if we became aware of extraterrestrial life?",
"What should we do with Battersea power station?",
"What use is poetry?",
"Do we learn more about the world from fiction than from non-fiction?",
"Can something be beautiful if it is not fit for purpose?",
"Are reports of the death of the book greatly exaggerated?",
"‘Poetry attaches its emotion to the idea; the idea is the fact’ [MATTHEW ARNOLD] Discuss",
"Have independent central banks been a failure?",
"How long a period should elapse before it is acceptable for archaeologists to disinter human remains?",
"Are reparations a form of punishment?",
"Is it rational to fear your own death?",
"Should there be a legal remedy for persons who suffer losses as a result of the abandonment of election promises made by a political party elected into government?",
"How do we know whether or not prison works?",
"Should there be any restrictions on who can sit on a jury?",
"Should sex offenders remain for life on the sex offenders register?",
"Discuss what philosophy can learn from and contribute to some other academic discipline",
"Are there any philosophical arguments which succeed in undermining what we ordinarily believe?",
"Should philosophers aim to provide a world view?",
"Should ethics make us better people?",
"Must historians make moral judgements?",
"Can monarchies be republics?",
"Will China avoid the fate of the Soviet Union?",
"Assess the significance of dictionaries and encyclopaedias for the study of history",
"What can the social sciences discover by better mapping of the brain and its operations?",
"Of what value is truth?",
"‘Democracy is being subverted by unaccountable judges who are sidelining Parliament’ ",
"Do you agree?",
"Why does Ovid’s popularity fluctuate?",
"‘A science of politics is not so much impossible as undesirable’ Discuss",
"If this were the last piece of paper available, what would you write on it?",
"Why is gold valuable?",
"Should there be a maximum, as well as a minimum, wage?",
"What should be the role of public libraries in Britain today?",
"Have the baby boomers betrayed their children?",
"Should the consequences of the recent earthquake in Japan change our minds about ",
"nuclear energy?",
"What is the future of the printed book?",
"Should faith schools be encouraged?",
"What is wrong with plagiarism?",
"Is it meaningful to speak of a ‘morality of architecture’?",
"Should we celebrate suburbia?",
"‘There is a certain incompatibility between the terms “cinema” and “Britain”’ [FRANÇOIS TRUFFAUT] Discuss",
"Should we encourage the re-introduction of locally extinct species?",
"Is there more to bel canto opera than fine singing?",
"How would you account for the current obsession with Caravaggio?",
"‘One of the under-appreciated tragedies of our time has been the sundering of our society from its past’ [MICHAEL GOVE] Discuss",
"Is the internet changing the ways in which we think?",
"Why are some jokes funnier than others?",
"Is boredom unfairly maligned?",
"‘who pays any attention / to the syntax of things / will never wholly kiss you’ [ee cummings] Discuss",
"Should the law help celebrities to prevent publication of their sexual indiscretions?",
"Do you agree with Thomas Hardy that ‘It is better to fail in poetry than to succeed in prose’?",
"Is it possible to write a history of homosexuality?",
"Did the wrong side win the Battle of Waterloo? ",
"What obligations, if any, do individuals owe to international institutions?",
"What are the strengths and limitations of studying the reception history of texts?",
"How should the press be regulated?",
"Why does fiction so often involve imagining the future?",
"Is Magna Carta still important?",
"When should insurance premiums not be based on actuarial risk?",
"What was ‘exceptional’ about American history?",
"What would Pindar have made of the  London Olympics?",
"Which is more important in the law, certainty or justice?",
"‘Historically, religion has been for women what politics has been for men’ Discuss ",
"Has contemporary philosophy anything to do with the love of wisdom?",
"Should judges be elected?",
"‘I thought how unpleasant it is to be locked out; and I thought how it is worse, perhaps, ",
"Is misfortune an irational concept?",
"What would the ancient world have made of the recent financial crisis?",
"Was there an ancient concept of ‘environmentalism’?",
"Is there any reason why films about the ancient world should be studied in a classics department rather than a film studies department?",
"What can game theory teach us about international relations?",
"‘Fundamentally, mainstream microeconomics is a “just world” theory, in which everyone gets what he or she deserves’ Do you agree?",
"Did economics save us from another Great Depression?",
"Is ‘World Literature’ an ersatz concept?",
"‘Many a single word also is itself a concentrated poem, having stores of poetical thought and imagery laid up in it’ [RC TRENCH] Discuss",
"What is the difference between literature and belles lettres?",
"Can travel writing be literature? ",
"What’s wrong with doping? ",
"Can there be a purely aesthetic appreciation of religious art?",
"Devise a new punctuation mark – and defend it ",
"Who is the most overrated figure in your discipline?",
"What is the most important unanswered question in philosophy?",
"How flexible should a constitution be?",
"Why didn’t the ancient world permit same-sex marriage?",
"Do future generations have rights? ",
"What can be learnt about literature from thinking about libraries?",
"Have modern chefs much to learn from ancient cookery?",
"Why should we value privacy?",
"‘O tell me the truth about love’ [WH AUDEN]",
"How do you know whether you are happy?",
"When is a gift too generous?",
"Why do so many people want to get married?",
"Should public servants get bonuses?",
"‘You cannot spend money in luxury without doing good to the poor’ [SAMUEL ",
"JOHNSON, attributed] Discuss",
"What is most likely to bring about the extinction of the human race?",
"Are all Internet users equal?",
"Is jazz America’s classical music?",
"‘Actors should be treated like cattle’ [ALFRED HITCHCOCK] Discuss",
"Explain the power of fundamentalist religion",
"Should we engineer our athletes?",
"Do we police disciplinary boundaries too rigorously?",
"Have historical novelists done more than historians to recover the life and texture of the past?",
"Is the UN correct to identify linguistic diversity as a basic human good?",
"Is the financial sector larger than it should be?",
"‘Changes in attitudes towards the human body have been vastly exaggerated’ Discuss ",
"Can we be forced to be free?",
"‘Human behaviour remains the same, but “vices” change’ Discuss",
"How can words be beautiful?",
"Should the judiciary be representative of the society which it serves?",
"Can policy rely on human rationality?",
"What has the Occupy movement revealed?",
"Should philosophy be taught in schools?",
"Are human rights universal?",
"Are any universal human traits manifested in tragedy?",
"‘A non-whiggish history of science, medicine and technology is an exercise in futility’ Discuss",
"Has the jury system outlived its utility?",
"Examine the intellectual relationship, if any, between history and economics",
"Do counterfeit goods have value?",
"Do modern university syllabuses unfairly neglect ancient medical writers? ",
"How much blame should academic economists take for the financial crisis? ",
"Does it matter if national identities wither away? ",
"‘The only obligation we have to the past is to re-write it’ [OSCAR WILDE] Discuss ",
"Should investors be able to fund legal actions in exchange for a share of the damages? ",
"What is the role of metaphor in science?",
"Is the brain a computer?",
"Did death evolve?",
"Is technology the enemy of history?",
"How would your subject be different if women had always been equal in power to men?",
"to be locked in’ [VIRGINIA WOOLF] Are the best writers outsiders?",
"Is politics philosophy in action? ",
"Are exceptions part of the rule?",
"Is the main thing that divides economists their political beliefs?",
"There is evidence that people give more to charity when asked by someone wearing a designer label What should we make of this?",
"What is special about José Mourinho?",
"Why are the deaf members of a given society more likely to develop a distinct subculture than its blind members?",
"Can assassination ever be a proper instrument of foreign policy?",
"Is caricature an act of aggression?",
"For what should we celebrate the King James Bible?",
"Is militant atheism just another form of religious extremism?",
"Could my brain be evil?",
"Can we afford to support science at the cost of the humanities?",
"Has obesity taken over from smoking?",
"Is self contradiction inevitable",
"Is higher education a public service or a business?",
"Is ‘Red Toryism’ a contradiction in terms?",
"Should governments aspire to make their citizens happy?",
"If you were Prime Minister, what considerations would you take into account in deciding the size and composition of your Cabinet?",
"Could there be a highest form of art? ",
"Should I care how many medals my country wins at the Olympics? ",
"How much would you like to know about your own DNA sequence? ",
"Is it unethical to exaggerate in a letter of recommendation, when it is anticipated that what is said will be discounted? ",
"Humanity is too extremely developed for its corporeal conditions  this planet does not supply the material for happiness’ Do you agree? ",
"Should I be convinced by a scientific argument I don’t understand? ",
"‘Have nothing in your houses that you do not know to be useful, or believe to be beautiful’ [WILLIAM MORRIS] Is this good advice? ",
"Should ‘work’ and ‘life’ be balanced? ",
"Can music be immoral? ",
"Is there anything wrong with pursuing one’s social life through an online avatar? ",
"Should we discourage child prodigies? ",
"What does it mean for ‘society’ to be ‘Big’? ",
"‘We who hate change survive Only through change’ [CHRISTOPHER LOGUE] Discuss ",
"Should rival football fans be allowed to fight each other if they all want to? ",
"Is it wise to try to make contact with alien life forms? ",
"Is Wikipedia an encyclopaedia? ",
"Does Britain undervalue grands projets? ",
"Can charity be selfish? ",
"Do animals that make tools teach us anything about ourselves? ",
"‘It seems to me that one of the kindest things that parents can do for their children is to die relatively young’ [AUBERON WAUGH] Is it? ",
"Is climate change denial heresy? ",
"Is the development of 3D cinema anything more than a gimmick? ",
"what of luck?",
"Is inheritance and ethical issue?",
"‘I maintain music is not here to make us forget about life It is here to teach us about ",
"life’ [DANIEL BARENBOIM] How might it do that?",
"‘To know God’s nature one would have to be God Himself’ [JOSEPH ALBO] Is philosophy of religion therefore futile? ",
"Why are social inequalities so widely accepted? ",
"What role, if any, should hatred play in our ethical lives? ",
"‘A “new” play by Shakespeare? I’d prefer a new play by somebody else’ [DAVID MITCHELL] Would you? ",
"Should people be paid according to their capabilities, their effort or something else? ",
"Would an ancient Athenian consider modern Britain democratic? ",
"Is there any point in distinguishing ‘literature’ from other kinds of writing? ",
"In what sense (if any) have the members of the baby boom generation ‘stolen their children’s future’ [DAVID WILLETTS]? ",
"What is the place of common sense in philosophy? ",
"Should the police be made accountable to elected politicians? ",
"Did the ancient world have a concept of child abuse? ",
"Is fairness a relevant concept for economics? ",
"Should Texas declare independence? ",
"Should it be possible to pursue scientific arguments through libel law? ",
"Can historical novels be good novels and good history? ",
"Are the Americans the Romans of the modern world? ",
"Should religious convictions excuse breaches of legal duties? ",
"‘History does not need explanatory principles only words to tell how things are’ [ELIE KEDOURIE] do you agree? ",
"Should scientists even try to predict the future? ",
"What are the moral obligations of the biographer? ",
"Should England declare independence? ",
"Does development aid do more harm than good?",
"Could a reduction in income inequality improve the health and wellbeing of a whole nation?",
"Are bankers or politicians more to blame for the present world economic crisis?",
"Does it matter whether there is life elsewhere in the universe?",
"„There was a time when people simply wanted to sense the moon, but now they want to see it‟ [GOETHE] Discuss",
"Should science be subject to democratic control?",
"What is the significance of binge drinking?",
"Is maternity leave good for women?",
"Should Jade Goody be in the Oxford Dictionary of National Biography?",
"„Gender is a primary way of signifying relationships of power‟ [JOAN W SCOTT, ] Is this still the case?",
"„Wild law‟: if animals have rights, can nature have rights too?",
"What or who are your discipline's false gods? ",
"Would anyone in the ancient world have understood „team spirit‟?",
"Do EITHER ancient writers OR ancient artists OR ancient philosophers have anything in common with their modern counterparts?",
"Would it have been better had some surviving works of ancient authors been lost?",
"Anatole Kaletsky wrote: „It is now time for what historians of science call a “paradigm shift”‟ [The Times, February ] Discuss",
"Is the popularization of classical culture in modern cinema of any value?",
"What is the function of criticism at the present time?",
"Does pleasure always have a cultural function?",
"„A people that grows accustomed to sloppy writing is a people in process of losing grip on its empire and on itself‟ [EZRA POUND] Discuss",
"Is lexicography a science or an art?",
"While considering the capacity of economics to explain recent economic events, ",
"Is it useful to talk in terms of the „bottom billion‟ of the world‟s poorest people?",
"Is capitalism inherently unstable?",
"What can economics contribute to legal theory and practice? ",
"What understandings of the past may be unlocked by the concept of „masculinity‟?",
"If archaeologists and historians communicated better with each other, which would gain more?",
"„I often think it odd that it should be so dull, for a great deal of it must be invention‟ [JANE AUSTEN on history] Discuss",
"Does style matter in historical writing?",
"Should the law prohibit assisting the suicide of a mentally competent adult?",
"Should people accused of serious criminal offences be entitled to anonymity unless and until convicted?",
"What is the difference between property and wealth?",
"Is there too much law?",
"Why should we be concerned about the welfare of future generations?",
"Is there any place left for system-building in philosophy?",
"Is clarity essential to philosophy?",
"Common sense is the metaphysics of the Stone Age‟ [BERTRAND RUSSELL] Discuss",
"If power corrupts, how should institutions be designed?",
"What role should loyalty play in politics?",
"Is politics a job, a profession, or a vocation?",
"What does sovereignty mean today?",
"Do different disciplines have different concepts of causation?",
"Why does truth matter?",
"Should university education be free?",
"How many people should there be?",
"Do developing countries have a greater right to pollute the environment?",
"Does contemporary aesthetics need a concept of beauty?",
"How can an examination of an artist‟s life help us to appraise his or her artistic achievements?",
"„The ability to access the Web will be either a great divider or a great equaliser‟ [TIM BERNERS-LEE, ] Discuss",
"Does Facebook put the private sphere in jeopardy?",
"What are the functions of fashion?",
"Is there something inherently coarsening about sport?",
"Why doesn‟t Britain have a café culture?",
"What is the value of „red top‟ journalism?",
"„Ah, but a man‟s reach should exceed his grasp Or what‟s a heaven for?‟ [ROBERT BROWNING] Discuss",
"Has morality made progress? ",
"Is it ethical to abort foetuses with Down‟s syndrome?",
"Whither feminism?",
"Explain the importance of studying the humanities in a letter to a living politician of your choice",
"Reform the House of Lords",
"Can conservatism be a force for good in an academic institution?",
"What’s so bad about envy?",
"What’s so good about creativity?",
"Is altruism really a form of self-interest?",
"Did the left or the right win the twentieth century?",
"Should intellectuals tweet?",
"Should states control their borders? ",
"Is vegetarianism the future? ",
"Should all citizens receive a basic income from the state? ",
"Should airlines be permitted to charge passengers according to their weight? ",
"‘Secure people dare’ Do they? ",
"Should prisoners be allowed to watch television? ",
"What, if anything, is wrong with using drones in warfare? ",
"What are universities for?",
"What shapes urban landscapes?",
"Should scientific progress make us optimistic? ",
"Is France the sick man of Europe? ",
"Is gardening art? ",
"Is globalization undermining democracy? ",
"What role should disgust play in our moral decision-making? ",
"Is it wrong to change your accent? ",
"Is the middle class a force for good? ",
"Defend kitsch ",
"Should tackling corruption be the first priority for developing countries?",
"‘Fiction’s about what it is to be a fucking human being’ [DAVID FOSTER WALLACE] Is it? ",
"How should we listen to music? ",
"What will become of the English? ",
"Is globalization just Pax Americana?",
"„All political careers end in failure‟ [J ENOCH POWELL] Is this true?",
"Could there be a British Barack Obama?",
"Do the innocent have nothing to fear?",
"Why are face transplants more controversial than liver transplants?",
"Is a generation gap inevitable?",
"„Thus said Alfred: “If you have a sorrow, do not tell it to your minion Tell it to your ",
"saddlebow, and ride forth singing”‟ [„Proverbs of Alfred‟, thirteenth century] Is a stiff upper lip a good thing?",
"Can you take the religion out of religious art?"]



var interval, i = 1;

//function dostuff() {
    
T.post('statuses/update', { status: twitterArray[i] }, function(err, data, response) {
  console.log(data)
});

    if(i < twitterArray.length) i++;
    else clearInterval(interval);


interval = setInterval(dostuff, 86400000);